{"name": "Проверка получения количества заказов \"total\" для авторизованного пользователя - нет заказов", "status": "broken", "statusDetails": {"message": "NameError: name 'auth_token' is not defined", "trace": "self = <test_get_user_orders.TestGetUserOrders object at 0x104c60e00>\nsetup_user = ({'email': 'ajsqcaetwx@mail.ru', 'name': 'ldemcirtbg', 'password': 'yhvaypozlf'}, 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6...WIxOWVkMjgwMDAxYjQ2MDU1ZSIsImlhdCI6MTcyMDA3ODAwMSwiZXhwIjoxNzIwMDc5MjAxfQ.KLhCVsWf8jKc7pkfwJ6V-4tYGTXT0HfWGtnu8lhhQ7w')\n\n    @allure.title('Проверка получения количества заказов \"total\" для авторизованного пользователя - нет заказов')\n    def test_get_user_orders_total_authorized_user_no_orders(self, setup_user):\n>       response = HelpersOnCreateUser.try_to_get_user_orders(auth_token)\nE       NameError: name 'auth_token' is not defined\n\ntests/test_get_user_orders.py:87: NameError"}, "start": 1720078001925, "stop": 1720078001925, "uuid": "627fb400-7f2e-4cdd-82f8-19deac265881", "historyId": "bf77a96ca810b481603598123bca33d4", "testCaseId": "bf77a96ca810b481603598123bca33d4", "fullName": "tests.test_get_user_orders.TestGetUserOrders#test_get_user_orders_total_authorized_user_no_orders", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_ingredients', scope='class')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "MacBook-Air-Lapka.local"}, {"name": "thread", "value": "7394-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}